@Dointo.AiRecruiter.RestApi_HostAddress = https://localhost:7072

GET {{Dointo.AiRecruiter.RestApi_HostAddress}}/weatherforecast/
Accept: application/json
###
GET {{Dointo.AiRecruiter.RestApi_HostAddress}}/openapi/v1.json
###
GET {{Dointo.AiRecruiter.RestApi_HostAddress}}/api/jobPosts
Accept:application/json