@Dointo.AiRecruiter.RestApi_HostAddress = http://localhost:5275

GET {{Dointo.AiRecruiter.RestApi_HostAddress}}/weatherforecast/
Accept: application/json
###
GET {{Dointo.AiRecruiter.RestApi_HostAddress}}/openapi/v1.json
