name: Validate Server Code

on: [pull_request]

jobs:
  build:
    runs-on: windows-latest

    env:
      CODE_PATH: "src/AiRecruiterCodeBase/"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List complete directory tree for debugging
        run: |
          echo "Listing complete directory tree:"
          tree

      - name: List files in CODE_PATH for debugging
        run: |
          echo "Listing files in CODE_PATH:"
          tree ${{ env.CODE_PATH }}

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.x"

      - name: Restore Packages
        run: dotnet restore ${{ env.CODE_PATH }}**/*.csproj

      - name: Build
        run: dotnet build ${{ env.CODE_PATH }}**/*.csproj --configuration Release /p:Version=${{ github.run_number }}

      - name: Test
        run: dotnet test ${{ env.CODE_PATH }}**.[Tt]ests/*.csproj --configuration Release --collect "Code coverage"

      - name: Publish Code Coverage
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: ${{ runner.temp }}/**/*.coverage
